Add argbash template for, and newly generated cgreen-debug

diff --git a/tools/cgreen-debug b/tools/cgreen-debug
--- a/tools/cgreen-debug
+++ b/tools/cgreen-debug
@@ -1,106 +1,116 @@
-#!/bin/bash
+# cgreen-debug
 #
-# cgreen-debug is a script to helt debugging Cgreen tests.
+# Script to start cgreen-runner under gdb, load a library and break
+# on a named test.
 #
-# Run your tests with the cgreen-runner as usual. Find the name of the
-# test you want to debug. Convert the breadcrum form (Context -> Test)
-# to commandline form (Context:Test) and run cgreen-debug like this:
-#
-#     cgreen-debug <library> <test>
-#
-#
-# This is a positional arguments-only example of Argbash potential
-#
+
+# This is actually not that script, but a template for argbash
+# (https://argbash.io) which generates argument parsing capable bash
+# scripts from a template just like this.
+
+# To generate a new 'cgreen-debug' use 'argbash cgreen-debug.argbash -o cgreen-debug'
+# if you have argbash installed, or go to https://argbash.io and paste this file
+# into the online version.
+
 # ARG_HELP([Start cgreen-runner under GDB and break at a specific test])
-# ARG_POSITIONAL_SINGLE([library],[Dynamically loadable library with Cgreen tests])
-# ARG_POSITIONAL_SINGLE([testname],[The test in Cgreen notation ('<Context>:<test>') to debug])
+# ARG_POSITIONAL_SINGLE([library],[Dynamically loadable library with Cgreen tests],[])
+# ARG_POSITIONAL_SINGLE([testname],[The test to debug, in Cgreen notation ('<Context>:<test>')],[])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.6.1 one line above ###
+### START OF CODE GENERATED BY Argbash v2.7.1 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
-# Generated online by https://argbash.io/generate
+
 
 die()
 {
-    local _ret=$2
-    test -n "$_ret" || _ret=1
-    test "$_PRINT_HELP" = yes && print_help >&2
-    echo "$1" >&2
-    exit ${_ret}
+	local _ret=$2
+	test -n "$_ret" || _ret=1
+	test "$_PRINT_HELP" = yes && print_help >&2
+	echo "$1" >&2
+	exit ${_ret}
 }
+
 
 begins_with_short_option()
 {
-    local first_option all_short_options
-    all_short_options='h'
-    first_option="${1:0:1}"
-    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+	local first_option all_short_options='h'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
-
-
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 
-print_help ()
-{
-    printf '%s\n\n' "Start cgreen-runner under GDB and break at a specific test"
-    printf 'Usage: %s [-h|--help] <library> <testname>\n\n' "$(basename -- $0)"
-    printf '\t%s\n' "<library>: Dynamically loadable library with Cgreen tests"
-    printf '\t%s\n' "<testname>: The test in Cgreen notation ('<Context>:<test>') to debug"
-    printf '\t%s\n\n' "-h,--help: Prints help"
-}
 
-parse_commandline ()
+print_help()
 {
-    while test $# -gt 0
-    do
-        _key="$1"
-        case "$_key" in
-            -h|--help)
-                print_help
-                exit 0
-                ;;
-            -h*)
-                print_help
-                exit 0
-                ;;
-            *)
-                _positionals+=("$1")
-                ;;
-        esac
-        shift
-    done
+	printf '%s\n' "Start cgreen-runner under GDB and break at a specific test"
+	printf 'Usage: %s [-h|--help] <library> <testname>\n' "$0"
+	printf '\t%s\n' "<library>: Dynamically loadable library with Cgreen tests"
+	printf '\t%s\n' "<testname>: The test to debug, in Cgreen notation ('<Context>:<test>')"
+	printf '\t%s\n' "-h, --help: Prints help"
 }
 
 
-handle_passed_args_count ()
+parse_commandline()
 {
-    _required_args_string="'library' and 'testname'"
-    test ${#_positionals[@]} -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
-    test ${#_positionals[@]} -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
+	_positionals_count=0
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_last_positional="$1"
+				_positionals+=("$_last_positional")
+				_positionals_count=$((_positionals_count + 1))
+				;;
+		esac
+		shift
+	done
 }
 
-assign_positional_args ()
-{
-    _positional_names=('_arg_library' '_arg_testname' )
 
-    for (( ii = 0; ii < ${#_positionals[@]}; ii++))
-    do
-        eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
-    done
+handle_passed_args_count()
+{
+	local _required_args_string="'library' and 'testname'"
+	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+}
+
+
+assign_positional_args()
+{
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_library _arg_testname "
+
+	shift "$_shift_for"
+	for _positional_name in ${_positional_names}
+	do
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
+	done
 }
 
 parse_commandline "$@"
 handle_passed_args_count
-assign_positional_args
+assign_positional_args 1 "${_positionals[@]}"
 
 # OTHER STUFF GENERATED BY Argbash
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
+
 
 bp=${2//:/__}
 echo break $bp > .cgreen-debug-commands
@@ -112,3 +122,5 @@ else
 fi
 $debugger -ex "set breakpoint pending on" cgreen-runner --command=.cgreen-debug-commands
 rm .cgreen-debug-commands
+
+# ] <-- needed because of Argbash
