[tools][debug] Add a --debugger option to cgreen-debug
This might actually help with #249

diff --git a/tools/cgreen-debug b/tools/cgreen-debug
--- a/tools/cgreen-debug
+++ b/tools/cgreen-debug
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 # cgreen-debug
 #
 # Script to start cgreen-runner under gdb, load a library and break
@@ -21,29 +21,30 @@
 # if you have argbash installed, or go to https://argbash.io and paste
 # this file into the online version.
 
-# ARG_HELP([Start cgreen-runner under GDB and break at a specific test])
+# ARG_HELP([Start cgreen-runner under GDB (or other debugger) and break at a specific test])
+# ARG_OPTIONAL_SINGLE([debugger],[d],[The debugger to use],[cgdb])
 # ARG_POSITIONAL_SINGLE([library],[Dynamically loadable library with Cgreen tests],[])
 # ARG_POSITIONAL_SINGLE([testname],[The test to debug, in Cgreen notation ('<Context>:<test>')],[])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.7.1 one line above ###
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
 
 
 die()
 {
-    local _ret=$2
-    test -n "$_ret" || _ret=1
-    test "$_PRINT_HELP" = yes && print_help >&2
+    local _ret="${2:-1}"
+    test "${_PRINT_HELP:-no}" = yes && print_help >&2
     echo "$1" >&2
-    exit ${_ret}
+    exit "${_ret}"
 }
 
 
 begins_with_short_option()
 {
-    local first_option all_short_options='h'
+    local first_option all_short_options='hd'
     first_option="${1:0:1}"
     test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -51,15 +52,17 @@ begins_with_short_option()
 # THE DEFAULTS INITIALIZATION - POSITIONALS
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
+_arg_debugger="cgdb"
 
 
 print_help()
 {
-    printf '%s\n' "Start cgreen-runner under GDB and break at a specific test"
-    printf 'Usage: %s [-h|--help] <library> <testname>\n' "$0"
+    printf '%s\n' "Start cgreen-runner under GDB (or other debugger) and break at a specific test"
+    printf 'Usage: %s [-h|--help] [-d|--debugger <arg>] <library> <testname>\n' "$0"
     printf '\t%s\n' "<library>: Dynamically loadable library with Cgreen tests"
     printf '\t%s\n' "<testname>: The test to debug, in Cgreen notation ('<Context>:<test>')"
     printf '\t%s\n' "-h, --help: Prints help"
+    printf '\t%s\n' "-d, --debugger: The debugger to use (default: 'cgdb')"
 }
 
 
@@ -77,6 +80,17 @@ parse_commandline()
             -h*)
                 print_help
                 exit 0
+                ;;
+            -d|--debugger)
+                test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+                _arg_debugger="$2"
+                shift
+                ;;
+            --debugger=*)
+                _arg_debugger="${_key##--debugger=}"
+                ;;
+            -d*)
+                _arg_debugger="${_key##-d}"
                 ;;
             *)
                 _last_positional="$1"
@@ -124,10 +138,19 @@ assign_positional_args 1 "${_positionals[@]}"
 bp=${2//:/__}
 echo break $bp > .cgreen-debug-commands
 echo run $1 $2 >> .cgreen-debug-commands
-if command -v cgdb ; then
-    debugger=cgdb
+if [ "$_arg_debugger" == "" ]; then
+    if command -v cgdb > /dev/null 2>&1 ; then
+        debugger=cgdb
+    else
+        debugger=gdb
+    fi
 else
-    debugger=gdb
+    if command -v $_arg_debugger > /dev/null 2>&1 ; then
+        debugger=$_arg_debugger
+    else
+        echo "No such debugger: $_arg_debugger"
+        exit 1
+    fi
 fi
 $debugger -ex "set breakpoint pending on" cgreen-runner --command=.cgreen-debug-commands
 rm .cgreen-debug-commands
