Add missing argbash template and fixup description in it

diff --git a/tools/cgreen-debug b/tools/cgreen-debug
--- a/tools/cgreen-debug
+++ b/tools/cgreen-debug
@@ -5,11 +5,10 @@
 # on a named test.
 #
 
-# This is both that script but also a template for argbash
+# If you are viewing 'cgreen-debug' *is* that script. But if you are looking at
+# 'cgreen-debug.argbash' then this is actually a template for argbash
 # (https://argbash.io) which generates argument parsing capable bash
 # scripts from a template just like this.
-#
-# Actual script is at the bottom of this file.
 
 # To generate a new 'cgreen-debug' use 'argbash cgreen-debug.argbash -o cgreen-debug'
 # if you have argbash installed, or go to https://argbash.io and paste this file
@@ -27,19 +26,19 @@
 
 die()
 {
-    local _ret=$2
-    test -n "$_ret" || _ret=1
-    test "$_PRINT_HELP" = yes && print_help >&2
-    echo "$1" >&2
-    exit ${_ret}
+	local _ret=$2
+	test -n "$_ret" || _ret=1
+	test "$_PRINT_HELP" = yes && print_help >&2
+	echo "$1" >&2
+	exit ${_ret}
 }
 
 
 begins_with_short_option()
 {
-    local first_option all_short_options='h'
-    first_option="${1:0:1}"
-    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+	local first_option all_short_options='h'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
 # THE DEFAULTS INITIALIZATION - POSITIONALS
@@ -49,60 +48,60 @@ _positionals=()
 
 print_help()
 {
-    printf '%s\n' "Start cgreen-runner under GDB and break at a specific test"
-    printf 'Usage: %s [-h|--help] <library> <testname>\n' "$0"
-    printf '\t%s\n' "<library>: Dynamically loadable library with Cgreen tests"
-    printf '\t%s\n' "<testname>: The test to debug, in Cgreen notation ('<Context>:<test>')"
-    printf '\t%s\n' "-h, --help: Prints help"
+	printf '%s\n' "Start cgreen-runner under GDB and break at a specific test"
+	printf 'Usage: %s [-h|--help] <library> <testname>\n' "$0"
+	printf '\t%s\n' "<library>: Dynamically loadable library with Cgreen tests"
+	printf '\t%s\n' "<testname>: The test to debug, in Cgreen notation ('<Context>:<test>')"
+	printf '\t%s\n' "-h, --help: Prints help"
 }
 
 
 parse_commandline()
 {
-    _positionals_count=0
-    while test $# -gt 0
-    do
-        _key="$1"
-        case "$_key" in
-            -h|--help)
-                print_help
-                exit 0
-                ;;
-            -h*)
-                print_help
-                exit 0
-                ;;
-            *)
-                _last_positional="$1"
-                _positionals+=("$_last_positional")
-                _positionals_count=$((_positionals_count + 1))
-                ;;
-        esac
-        shift
-    done
+	_positionals_count=0
+	while test $# -gt 0
+	do
+		_key="$1"
+		case "$_key" in
+			-h|--help)
+				print_help
+				exit 0
+				;;
+			-h*)
+				print_help
+				exit 0
+				;;
+			*)
+				_last_positional="$1"
+				_positionals+=("$_last_positional")
+				_positionals_count=$((_positionals_count + 1))
+				;;
+		esac
+		shift
+	done
 }
 
 
 handle_passed_args_count()
 {
-    local _required_args_string="'library' and 'testname'"
-    test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
-    test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
+	local _required_args_string="'library' and 'testname'"
+	test "${_positionals_count}" -ge 2 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 2 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	test "${_positionals_count}" -le 2 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 2 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
 }
 
 
 assign_positional_args()
 {
-    local _positional_name _shift_for=$1
-    _positional_names="_arg_library _arg_testname "
+	local _positional_name _shift_for=$1
+	_positional_names="_arg_library _arg_testname "
 
-    shift "$_shift_for"
-    for _positional_name in ${_positional_names}
-    do
-        test $# -gt 0 || break
-        eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
-        shift
-    done
+	shift "$_shift_for"
+	for _positional_name in ${_positional_names}
+	do
+		test $# -gt 0 || break
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+		shift
+	done
 }
 
 parse_commandline "$@"
